server:
  address: "127.0.0.1"
  port: 58081
  gin_mode: release
  access_log: false

v2ray:
  # 不配置binary_path使用内置的xray
#  binary_path: "./bin/"
  config_path: "./data/xray.json"
  log_path: "./data/v2ray.log"


settings:
  data_path: "./data"
